
# Set this as the location where your Journal.json file is located
# Use single quotes to preserve the path as is
# The path can contain spaces
ROOT: '/path/to/day one journals'

# name of folder where journal entries will end up
JOURNAL_FOLDER: "Journal"
JOURNAL_JSON: "Journal.json"

# All fields below are optional. Set them to "" or remove them if not needed.

# Use first line (title) from entry text as the filename,
# If there is no text or only media, use the default filename
# Filename format: "title YYYY-MM-DD"
DEFAULT_FILENAME: Day One

# If there is no text at all, use the default text for the entry
DEFAULT_TEXT: "Empty day one entry. Keep it for record.\n"

# This will append DayOne/ as part of the tag name for sub-tags
# i.e. instead of #entry, it is #DayOne/entry. To exclude set to "".
# If you change DayOne to something else, make sure you keep the trailing /
TAG_PREFIX: "DayOne/"

# I like to keep this tag in addition to other tags from entries
# To exclude just remove it
ADDITIONAL_TAGS:
  - "From/DayOne"



